/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DetailSection: typeof import('./src/components/detail-section/detail-section.vue')['default']
    DropdownSelect: typeof import('./src/components/dropdown-select/dropdown-select.vue')['default']
    FavorListItem: typeof import('./src/components/favor-list-item/favor-list-item.vue')['default']
    FavorListItemInfo: typeof import('./src/components/favor-list-item-info/favor-list-item-info.vue')['default']
    FavorListItemTitle: typeof import('./src/components/favor-list-item-title/favor-list-item-title.vue')['default']
    HouseItemV3: typeof import('./src/components/house-item-v3/house-item-v3.vue')['default']
    HouseItemV9: typeof import('./src/components/house-item-v9/house-item-v9.vue')['default']
    Loading: typeof import('./src/components/loading/loading.vue')['default']
    MsgTip: typeof import('./src/components/msg-tip/msg-tip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search-bar/search-bar.vue')['default']
    SearchListItem: typeof import('./src/components/search-list-item/search-list-item.vue')['default']
    SearchListItemInfo: typeof import('./src/components/search-list-item-info/search-list-item-info.vue')['default']
    SearchListItemTitle: typeof import('./src/components/search-list-item-title/search-list-item-title.vue')['default']
    SideBar: typeof import('./src/components/side-bar/side-bar.vue')['default']
    TabBar: typeof import('./src/components/tab-bar/tab-bar.vue')['default']
    TabBar_01: typeof import('./src/components/tab-bar/tab-bar_01.vue')['default']
    TabBar_02: typeof import('./src/components/tab-bar/tab-bar_02.vue')['default']
    TabBar_03: typeof import('./src/components/tab-bar/tab-bar_03.vue')['default']
    TabControl: typeof import('./src/components/tab-control/tab-control.vue')['default']
    TabSelect: typeof import('./src/components/tab-select/tab-select.vue')['default']
    TabSelectItem: typeof import('./src/components/tab-select-item/tab-select-item.vue')['default']
    ToolBar: typeof import('./src/components/tool-bar/tool-bar.vue')['default']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanIcon: typeof import('vant/es')['Icon']
    VanIndexAnchor: typeof import('vant/es')['IndexAnchor']
    VanIndexBar: typeof import('vant/es')['IndexBar']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    ViewHouseBtns: typeof import('./src/components/view-house-btns/view-house-btns.vue')['default']
  }
}
